# Pengenalan Numpy

## Shape dan Dimensi dari Numpy Array

Memuali dengan menimport Numpy

In [3]:
import numpy as np

membuat numpy array sebanyak 10 digit

In [5]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

hasil diatas terlihat seperti list dari python dengan hanya 1 brackets. ini artinya hanya terdapat satu dimensi. cara melihat dimensi dari array.

In [6]:
array_1 = np.arange(10)
array_1.shape

(10,)

array mempunyai attribute **shape**. hasil diatas adalah sebuah tupple, yang mempupunyai panjang 1. banyaknya dimensi sama dengan panjang dari tuple.

In [7]:
array_1.ndim

1

array yang kita punya adalah sebanyak 10 elemen. mengubah bentuk dari array bisa dengan melakukan metode **reshape** 

In [17]:
array_1 = array_1.reshape((5,2))
array_1

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

metoe reshape diatas mengubah array menjadi 5x2 objek data yang terlihat seperti list dari list.

In [18]:
array_1.shape

(5, 2)

In [19]:
array_1.ndim

2

## NumPy Broadcasting

menambahkan 1 kesetiap elemen dari array dengan broadcasting. perhatikan bahwa perubah yang dilakukan tidak tesimpan

In [21]:
array_1+1

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

bentuk dari broadcasting mengarah ke pembentukan array yang berukuran kecil menjadi ukuran besar. contoh diatas menunjukkan, dengan skala 1 diregangkan menjadi bentuk 5x2 dan ditambahkan ke *array_1*

dibuat array baru yaitu *array_2*. perhatikan bahwa ketika kita mengalikan antar array, ini hanya menghasilkan perkalian silang antar elemen dari array, **bukan perkalian  marix**

In [40]:
array_2 = np.arange(10)
array_2 * array_2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

setiap elemen dikuaadratkan, terlihat seperti berikut

In [29]:
array_2**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [30]:
array_2**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [41]:
array_2 = (array_2**2).reshape((5,2))
array_2

array([[ 0,  1],
       [ 4,  9],
       [16, 25],
       [36, 49],
       [64, 81]], dtype=int32)

menjumlahkan antar array

In [42]:
array_1 + array_2

array([[ 0,  2],
       [ 6, 12],
       [20, 30],
       [42, 56],
       [72, 90]])

## Menginisialisasi NumPy arrays dan dtypes

Ada beberapa cara untuk mengisialisasi NumPy array disamping *np.arange* yaitu:

1. menginisialisasi sebuah array dengan elemen 0 menggunakan **np.zeros**. *np.zeros((5,2))* membuat 5x2 array dari 0

In [43]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

2. menginisialisasi array dari 1 menggunakan **np.ones**. kita perkenalkan perintah **dtype**, diatur menjadi **np.int**, untuk meyakinkan bahwa satu adalah numpy dengan tipe integer/bilangan bulat. perhatikan habwa pada scikit-learn, elemen di dalam arrays diekspekstasi sebagai **np.float**

In [44]:
np.ones((5,2),dtype=np.int)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

3. menggunaka **np.empty** untuk mengalokasikan memory untuk array denga  ukuran dan *dtype* yang spesifik, tetapi tidak mempunyai nilai inisial awal.

In [45]:
np.empty((5,2),dtype=np.float)

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])